//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseSink) DeepCopyInto(out *ClickHouseSink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseSink.
func (in *ClickHouseSink) DeepCopy() *ClickHouseSink {
	if in == nil {
		return nil
	}
	out := new(ClickHouseSink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClickHouseSink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseSinkList) DeepCopyInto(out *ClickHouseSinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClickHouseSink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseSinkList.
func (in *ClickHouseSinkList) DeepCopy() *ClickHouseSinkList {
	if in == nil {
		return nil
	}
	out := new(ClickHouseSinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClickHouseSinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseSinkSpec) DeepCopyInto(out *ClickHouseSinkSpec) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	in.Writer.DeepCopyInto(&out.Writer)
	in.Policy.DeepCopyInto(&out.Policy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseSinkSpec.
func (in *ClickHouseSinkSpec) DeepCopy() *ClickHouseSinkSpec {
	if in == nil {
		return nil
	}
	out := new(ClickHouseSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseSinkStatus) DeepCopyInto(out *ClickHouseSinkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseSinkStatus.
func (in *ClickHouseSinkStatus) DeepCopy() *ClickHouseSinkStatus {
	if in == nil {
		return nil
	}
	out := new(ClickHouseSinkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStreamRule) DeepCopyInto(out *ClusterStreamRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStreamRule.
func (in *ClusterStreamRule) DeepCopy() *ClusterStreamRule {
	if in == nil {
		return nil
	}
	out := new(ClusterStreamRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterStreamRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStreamRuleList) DeepCopyInto(out *ClusterStreamRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterStreamRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStreamRuleList.
func (in *ClusterStreamRuleList) DeepCopy() *ClusterStreamRuleList {
	if in == nil {
		return nil
	}
	out := new(ClusterStreamRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterStreamRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStreamRuleSpec) DeepCopyInto(out *ClusterStreamRuleSpec) {
	*out = *in
	in.StreamRuleSpec.DeepCopyInto(&out.StreamRuleSpec)
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStreamRuleSpec.
func (in *ClusterStreamRuleSpec) DeepCopy() *ClusterStreamRuleSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterStreamRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSpec) DeepCopyInto(out *ConnectionSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	if in.DialTimeout != nil {
		in, out := &in.DialTimeout, &out.DialTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ReadTimeout != nil {
		in, out := &in.ReadTimeout, &out.ReadTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSpec.
func (in *ConnectionSpec) DeepCopy() *ConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GVKSelector) DeepCopyInto(out *GVKSelector) {
	*out = *in
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GVKSelector.
func (in *GVKSelector) DeepCopy() *GVKSelector {
	if in == nil {
		return nil
	}
	out := new(GVKSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedactionRule) DeepCopyInto(out *RedactionRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedactionRule.
func (in *RedactionRule) DeepCopy() *RedactionRule {
	if in == nil {
		return nil
	}
	out := new(RedactionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3CredentialsSpec) DeepCopyInto(out *S3CredentialsSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3CredentialsSpec.
func (in *S3CredentialsSpec) DeepCopy() *S3CredentialsSpec {
	if in == nil {
		return nil
	}
	out := new(S3CredentialsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ObjectLockSpec) DeepCopyInto(out *S3ObjectLockSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ObjectLockSpec.
func (in *S3ObjectLockSpec) DeepCopy() *S3ObjectLockSpec {
	if in == nil {
		return nil
	}
	out := new(S3ObjectLockSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3RotationSpec) DeepCopyInto(out *S3RotationSpec) {
	*out = *in
	if in.MaxObjectBytes != nil {
		in, out := &in.MaxObjectBytes, &out.MaxObjectBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxObjectAge != nil {
		in, out := &in.MaxObjectAge, &out.MaxObjectAge
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3RotationSpec.
func (in *S3RotationSpec) DeepCopy() *S3RotationSpec {
	if in == nil {
		return nil
	}
	out := new(S3RotationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Sink) DeepCopyInto(out *S3Sink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Sink.
func (in *S3Sink) DeepCopy() *S3Sink {
	if in == nil {
		return nil
	}
	out := new(S3Sink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *S3Sink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3SinkList) DeepCopyInto(out *S3SinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]S3Sink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3SinkList.
func (in *S3SinkList) DeepCopy() *S3SinkList {
	if in == nil {
		return nil
	}
	out := new(S3SinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *S3SinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3SinkSpec) DeepCopyInto(out *S3SinkSpec) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(S3CredentialsSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Rotation.DeepCopyInto(&out.Rotation)
	if in.ObjectLock != nil {
		in, out := &in.ObjectLock, &out.ObjectLock
		*out = new(S3ObjectLockSpec)
		**out = **in
	}
	in.Writer.DeepCopyInto(&out.Writer)
	in.Policy.DeepCopyInto(&out.Policy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3SinkSpec.
func (in *S3SinkSpec) DeepCopy() *S3SinkSpec {
	if in == nil {
		return nil
	}
	out := new(S3SinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3SinkStatus) DeepCopyInto(out *S3SinkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3SinkStatus.
func (in *S3SinkStatus) DeepCopy() *S3SinkStatus {
	if in == nil {
		return nil
	}
	out := new(S3SinkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3WriterSpec) DeepCopyInto(out *S3WriterSpec) {
	*out = *in
	if in.QueueSize != nil {
		in, out := &in.QueueSize, &out.QueueSize
		*out = new(int32)
		**out = **in
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = new(int32)
		**out = **in
	}
	if in.EnqueueTimeout != nil {
		in, out := &in.EnqueueTimeout, &out.EnqueueTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DrainTimeout != nil {
		in, out := &in.DrainTimeout, &out.DrainTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3WriterSpec.
func (in *S3WriterSpec) DeepCopy() *S3WriterSpec {
	if in == nil {
		return nil
	}
	out := new(S3WriterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SinkPolicy) DeepCopyInto(out *SinkPolicy) {
	*out = *in
	if in.AllowedGVKs != nil {
		in, out := &in.AllowedGVKs, &out.AllowedGVKs
		*out = make([]GVKSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Redaction != nil {
		in, out := &in.Redaction, &out.Redaction
		*out = make([]RedactionRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SinkPolicy.
func (in *SinkPolicy) DeepCopy() *SinkPolicy {
	if in == nil {
		return nil
	}
	out := new(SinkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SinkReference) DeepCopyInto(out *SinkReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SinkReference.
func (in *SinkReference) DeepCopy() *SinkReference {
	if in == nil {
		return nil
	}
	out := new(SinkReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamRule) DeepCopyInto(out *StreamRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamRule.
func (in *StreamRule) DeepCopy() *StreamRule {
	if in == nil {
		return nil
	}
	out := new(StreamRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StreamRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamRuleList) DeepCopyInto(out *StreamRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StreamRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamRuleList.
func (in *StreamRuleList) DeepCopy() *StreamRuleList {
	if in == nil {
		return nil
	}
	out := new(StreamRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StreamRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamRuleSpec) DeepCopyInto(out *StreamRuleSpec) {
	*out = *in
	out.Sink = in.Sink
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]WatchedResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraRedaction != nil {
		in, out := &in.ExtraRedaction, &out.ExtraRedaction
		*out = make([]RedactionRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamRuleSpec.
func (in *StreamRuleSpec) DeepCopy() *StreamRuleSpec {
	if in == nil {
		return nil
	}
	out := new(StreamRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamRuleStatus) DeepCopyInto(out *StreamRuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamRuleStatus.
func (in *StreamRuleStatus) DeepCopy() *StreamRuleStatus {
	if in == nil {
		return nil
	}
	out := new(StreamRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchedResource) DeepCopyInto(out *WatchedResource) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchedResource.
func (in *WatchedResource) DeepCopy() *WatchedResource {
	if in == nil {
		return nil
	}
	out := new(WatchedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WriterSpec) DeepCopyInto(out *WriterSpec) {
	*out = *in
	if in.QueueSize != nil {
		in, out := &in.QueueSize, &out.QueueSize
		*out = new(int32)
		**out = **in
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = new(int32)
		**out = **in
	}
	if in.BatchMaxRows != nil {
		in, out := &in.BatchMaxRows, &out.BatchMaxRows
		*out = new(int32)
		**out = **in
	}
	if in.BatchMaxWait != nil {
		in, out := &in.BatchMaxWait, &out.BatchMaxWait
		*out = new(v1.Duration)
		**out = **in
	}
	if in.EnqueueTimeout != nil {
		in, out := &in.EnqueueTimeout, &out.EnqueueTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DrainTimeout != nil {
		in, out := &in.DrainTimeout, &out.DrainTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.CheckpointEvery != nil {
		in, out := &in.CheckpointEvery, &out.CheckpointEvery
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WriterSpec.
func (in *WriterSpec) DeepCopy() *WriterSpec {
	if in == nil {
		return nil
	}
	out := new(WriterSpec)
	in.DeepCopyInto(out)
	return out
}
